version: "3.10"
services:
  mlflow:
    build:
      context: .
      args:
        dst_model_path: "${REMOTE_MODEL_PATH}"
    image: mlflow_deployment
    container_name: mlflow_deployment-1
    ports:
      - "1234:1234"
    restart: always
